// Rakshak-Net CAD - Data Repository (Bhubaneswar Safety Grid)
// Designed for Enterprise Police/Government Operations Centers

window.RakshakData = {
  systemMetadata: {
    agency: "COMMISSIONERATE POLICE BHUBANESWAR-CUTTACK",
    division: "SPECIAL CITIZEN SAFETY & EMERGENCY RESPONSE UNIT (DIAL 112)",
    platformName: "RAKSHAK-NET CAD",
    version: "v3.4.1 (Enterprise Build 2026.09.09)",
    cadServerStatus: "OPERATIONAL",
    activeShift: "ALPHA-2 (18:00 - 02:00 IST)",
    dispatcherId: "DISPATCH-OFFICER-704",
    loraFrequencyBand: "IN865 (865.0 - 867.0 MHz)",
    encryptionStandard: "AES-128-GCM Hardware-Enforced"
  },

  // Active & Recent Incidents
  incidents: [
    {
      id: "RN-INC-2026-0941",
      timestamp: "2026-09-09 22:48:14 IST",
      elapsedSeconds: 218,
      status: "DISPATCHED",
      severity: "CRITICAL",
      type: "TRIPLE-PRESS PANIC TRIGGER",
      user: {
        name: "Priyanka Mohapatra",
        age: 23,
        regId: "OD-BBSR-CIT-9921",
        phone: "+91 98612 44321",
        emergencyContact: "Prasanta Mohapatra (Father) - +91 94370 88219",
        bloodGroup: "B+"
      },
      wearable: {
        deviceId: "RN-WR-9204",
        model: "Rakshak Band X1",
        battery: 89,
        batteryVoltage: "4.12V",
        accelerometer: { x: 2.84, y: -1.95, z: 0.88, jerkMagnitude: "3.56G" },
        heartRate: 138,
        triggerType: "Physical Triple Click + Sudden Jerk Acceleration",
        firmware: "v2.1.8-sec",
        rawHex: "0x7F4A92040188E4B192E0F103A899C74E"
      },
      location: {
        name: "Infocity Road, Near Magnetics Square, Patia",
        ward: "Ward 14 (Patia - Chandrasekharpur Zone)",
        lat: 20.3562,
        lng: 85.8174,
        accuracyRadiusMeters: 14.2,
        nearestLandmark: "Opposite Silicon Residency, Infocity Ave"
      },
      loraMesh: {
        receivingGateway: "GW-BBSR-01 (Patia High-Mast)",
        secondaryGateway: "GW-BBSR-02 (KIIT Square Pole)",
        rssi: -88,
        snr: 9.4,
        hopCount: 1,
        frequencyMhz: 865.200,
        spreadingFactor: "SF7 / BW 125kHz",
        packetDeliveryLatencyMs: 142
      },
      aiVerification: {
        confidenceScore: 94,
        threatLevel: "CONFIRMED_DISTRESS",
        acousticScore: 91,
        acousticDetail: "Acoustic panic signature detected (human scream frequency 3.1 kHz, SPL 86 dB)",
        opticalFlowScore: 96,
        opticalDetail: "CCTV Pole #14-B: Irregular rapid vector cluster detected; sudden deceleration pattern",
        wearableBioScore: 95,
        falseAlarmProbability: 6,
        status: "AUTO_VERIFIED_DISPATCH_TRIGGERED"
      },
      dispatch: {
        unitAssigned: "PCR-09",
        station: "Patia Police Station",
        officerInCharge: "Sub-Inspector R. K. Nayak",
        callsign: "PATIA-TIGER-9",
        distanceKm: 0.9,
        etaMinutes: 2.5,
        dispatchedAt: "22:48:42 IST",
        status: "EN_ROUTE",
        commsChannel: "VHF-CH-04 (Urban North)"
      }
    },
    {
      id: "RN-INC-2026-0938",
      timestamp: "2026-09-09 22:36:50 IST",
      elapsedSeconds: 902,
      status: "ON_SCENE",
      severity: "HIGH",
      type: "HIGH-G FALL & RAPID ROTATION",
      user: {
        name: "Subhashree Jena",
        age: 26,
        regId: "OD-BBSR-CIT-8140",
        phone: "+91 97760 11982",
        emergencyContact: "Rashmi Jena (Mother) - +91 94371 66201",
        bloodGroup: "O+"
      },
      wearable: {
        deviceId: "RN-WR-8812",
        model: "Rakshak Pendant Pro",
        battery: 74,
        batteryVoltage: "3.98V",
        accelerometer: { x: 4.12, y: -3.88, z: 1.10, jerkMagnitude: "5.76G" },
        heartRate: 142,
        triggerType: "Impact Sensor Threshold Exceeded (>4.5G)",
        firmware: "v2.1.4-sec",
        rawHex: "0x7F4A88120272B3F081D0A209B184D239"
      },
      location: {
        name: "Lane 4, KIIT Square Residential Perimeter",
        ward: "Ward 07 (KIIT Corridor)",
        lat: 20.3512,
        lng: 85.8155,
        accuracyRadiusMeters: 18.0,
        nearestLandmark: "Adjacent to Balaram Temple Junction"
      },
      loraMesh: {
        receivingGateway: "GW-BBSR-02 (KIIT Square Pole)",
        secondaryGateway: "GW-BBSR-01 (Patia High-Mast)",
        rssi: -94,
        snr: 7.8,
        hopCount: 2,
        frequencyMhz: 865.400,
        spreadingFactor: "SF8 / BW 125kHz",
        packetDeliveryLatencyMs: 188
      },
      aiVerification: {
        confidenceScore: 88,
        threatLevel: "ELEVATED_RISK",
        acousticScore: 82,
        acousticDetail: "Moderate acoustic spike (78 dB) followed by device impact transient",
        opticalFlowScore: 92,
        opticalDetail: "CAM-KIIT-09: Pedestrian collapse followed by two individuals approaching",
        wearableBioScore: 90,
        falseAlarmProbability: 12,
        status: "CONFIRMED_BY_SUPERVISOR"
      },
      dispatch: {
        unitAssigned: "PCR-14",
        station: "Infocity Police Post",
        officerInCharge: "Asst. Sub-Inspector M. Pattnaik",
        callsign: "INFOCITY-DELTA-14",
        distanceKm: 0.1,
        etaMinutes: 0.0,
        dispatchedAt: "22:37:25 IST",
        status: "ON_SCENE",
        commsChannel: "VHF-CH-04 (Urban North)"
      }
    },
    {
      id: "RN-INC-2026-0935",
      timestamp: "2026-09-09 22:15:02 IST",
      elapsedSeconds: 2210,
      status: "RESOLVED_FALSE_ALARM",
      severity: "LOW",
      type: "SINGLE-BUTTON HOLD (>6s)",
      user: {
        name: "Ananya Mishra",
        age: 21,
        regId: "OD-BBSR-CIT-5520",
        phone: "+91 99372 90118",
        emergencyContact: "Debasis Mishra (Brother) - +91 98610 22004",
        bloodGroup: "A+"
      },
      wearable: {
        deviceId: "RN-WR-4401",
        model: "Rakshak Band X1",
        battery: 92,
        batteryVoltage: "4.15V",
        accelerometer: { x: 0.08, y: 0.12, z: 0.98, jerkMagnitude: "0.99G" },
        heartRate: 78,
        triggerType: "Hold Button Press (No Motion Anomaly)",
        firmware: "v2.1.8-sec",
        rawHex: "0x7F4A44010190C11054E0B001F991E14A"
      },
      location: {
        name: "Damana Square, Chandrasekharpur BDA Colony",
        ward: "Ward 21 (CSPUR Central)",
        lat: 20.3245,
        lng: 85.8185,
        accuracyRadiusMeters: 8.5,
        nearestLandmark: "Near State Bank of India ATM"
      },
      loraMesh: {
        receivingGateway: "GW-BBSR-03 (CSPUR BDA Tower)",
        secondaryGateway: "GW-BBSR-07 (Jayadev Vihar Pole)",
        rssi: -76,
        snr: 12.1,
        hopCount: 1,
        frequencyMhz: 865.600,
        spreadingFactor: "SF7 / BW 125kHz",
        packetDeliveryLatencyMs: 95
      },
      aiVerification: {
        confidenceScore: 19,
        threatLevel: "BENIGN_IRREGULARITY",
        acousticScore: 14,
        acousticDetail: "Ambient traffic noise (54 dB); no distress phonetic formant detected",
        opticalFlowScore: 22,
        opticalDetail: "CAM-CSPUR-04: Static seated posture, no physical commotion or struggle",
        wearableBioScore: 21,
        falseAlarmProbability: 81,
        status: "AUTO_REJECTED_FALSE_ALARM"
      },
      dispatch: {
        unitAssigned: "NONE",
        station: "Chandrasekharpur PS",
        officerInCharge: "N/A",
        callsign: "NONE",
        distanceKm: 0,
        etaMinutes: 0,
        dispatchedAt: "--",
        status: "CLOSED",
        commsChannel: "--"
      }
    },
    {
      id: "RN-INC-2026-0929",
      timestamp: "2026-09-09 21:50:30 IST",
      elapsedSeconds: 3680,
      status: "RESOLVED",
      severity: "RESOLVED_SAFE",
      type: "TRIPLE-PRESS PANIC TRIGGER",
      user: {
        name: "Roshni Behera",
        age: 24,
        regId: "OD-BBSR-CIT-6619",
        phone: "+91 94373 77210",
        emergencyContact: "Santosh Behera (Father) - +91 94370 19283",
        bloodGroup: "B-"
      },
      wearable: {
        deviceId: "RN-WR-7719",
        model: "Rakshak Pendant Pro",
        battery: 68,
        batteryVoltage: "3.92V",
        accelerometer: { x: 1.95, y: -2.10, z: 1.45, jerkMagnitude: "3.22G" },
        heartRate: 124,
        triggerType: "Manual Panic Activation",
        firmware: "v2.1.4-sec",
        rawHex: "0x7F4A77190280D41299C0F108C712A902"
      },
      location: {
        name: "Janpath Road, Near Ram Mandir Square",
        ward: "Ward 32 (Saheed Nagar / Unit 3)",
        lat: 20.2885,
        lng: 85.8420,
        accuracyRadiusMeters: 11.0,
        nearestLandmark: "Near Khadim Showroom, Janpath"
      },
      loraMesh: {
        receivingGateway: "GW-BBSR-04 (Saheed Nagar Pole)",
        secondaryGateway: "GW-BBSR-05 (Master Canteen Pole)",
        rssi: -82,
        snr: 10.4,
        hopCount: 1,
        frequencyMhz: 865.200,
        spreadingFactor: "SF7 / BW 125kHz",
        packetDeliveryLatencyMs: 115
      },
      aiVerification: {
        confidenceScore: 89,
        threatLevel: "RESOLVED_INCIDENT",
        acousticScore: 86,
        acousticDetail: "Crowd verbal altercation acoustic signature corroborated",
        opticalFlowScore: 91,
        opticalDetail: "CAM-JANPATH-02: Stalking subject intercepted by PCR-07 patrol officers",
        wearableBioScore: 90,
        falseAlarmProbability: 11,
        status: "ACTION_COMPLETED_SAFE"
      },
      dispatch: {
        unitAssigned: "PCR-07",
        station: "Saheed Nagar Police Station",
        officerInCharge: "Inspector T. K. Dash",
        callsign: "SAHEED-EAGLE-7",
        distanceKm: 0.0,
        etaMinutes: 0.0,
        dispatchedAt: "21:51:10 IST",
        status: "RESOLVED_SAFE",
        commsChannel: "VHF-CH-02 (Central Capital)"
      }
    }
  ],

  // Municipal LoRa Relay Gateways across Bhubaneswar
  gateways: [
    {
      id: "GW-BBSR-01",
      name: "Patia Telecom High-Mast",
      poleRef: "OD-BMC-POLE-8841",
      ward: "Ward 14 (Patia)",
      coords: [20.3582, 85.8180],
      status: "ONLINE",
      frequency: "865.200 MHz",
      bandwidth: "125 kHz",
      currentLoadPktsPerMin: 44,
      avgRssi: -84,
      snr: 9.8,
      meshPeers: ["GW-BBSR-02", "GW-BBSR-03"],
      uptimePercentage: "99.94%",
      solarBatteryHealth: "98% (27.4V Solar Float)",
      lastKeepAlive: "4 seconds ago"
    },
    {
      id: "GW-BBSR-02",
      name: "KIIT Square Traffic Mast",
      poleRef: "OD-BMC-POLE-8848",
      ward: "Ward 07 (KIIT Corridor)",
      coords: [20.3535, 85.8160],
      status: "ONLINE",
      frequency: "865.400 MHz",
      bandwidth: "125 kHz",
      currentLoadPktsPerMin: 59,
      avgRssi: -81,
      snr: 10.5,
      meshPeers: ["GW-BBSR-01", "GW-BBSR-03"],
      uptimePercentage: "99.98%",
      solarBatteryHealth: "100% (Mains Power + UPS)",
      lastKeepAlive: "2 seconds ago"
    },
    {
      id: "GW-BBSR-03",
      name: "CSPUR BDA Housing Tower",
      poleRef: "OD-BMC-POLE-7210",
      ward: "Ward 21 (CSPUR)",
      coords: [20.3245, 85.8185],
      status: "ONLINE",
      frequency: "865.600 MHz",
      bandwidth: "125 kHz",
      currentLoadPktsPerMin: 38,
      avgRssi: -87,
      snr: 8.9,
      meshPeers: ["GW-BBSR-01", "GW-BBSR-02", "GW-BBSR-07"],
      uptimePercentage: "99.89%",
      solarBatteryHealth: "96% (26.8V Solar Float)",
      lastKeepAlive: "7 seconds ago"
    },
    {
      id: "GW-BBSR-04",
      name: "Saheed Nagar Janpath Overhead",
      poleRef: "OD-BMC-POLE-5512",
      ward: "Ward 32 (Saheed Nagar)",
      coords: [20.2885, 85.8420],
      status: "ONLINE",
      frequency: "865.200 MHz",
      bandwidth: "125 kHz",
      currentLoadPktsPerMin: 62,
      avgRssi: -79,
      snr: 11.2,
      meshPeers: ["GW-BBSR-05", "GW-BBSR-07"],
      uptimePercentage: "99.91%",
      solarBatteryHealth: "99% (Mains + LiFePO4)",
      lastKeepAlive: "1 second ago"
    },
    {
      id: "GW-BBSR-05",
      name: "Master Canteen Smart City Pole",
      poleRef: "OD-BMC-POLE-4109",
      ward: "Ward 40 (Railway Station Zone)",
      coords: [20.2645, 85.8390],
      status: "ONLINE",
      frequency: "865.800 MHz",
      bandwidth: "125 kHz",
      currentLoadPktsPerMin: 51,
      avgRssi: -83,
      snr: 9.6,
      meshPeers: ["GW-BBSR-04", "GW-BBSR-06"],
      uptimePercentage: "99.85%",
      solarBatteryHealth: "94% (Grid Connected)",
      lastKeepAlive: "3 seconds ago"
    },
    {
      id: "GW-BBSR-06",
      name: "Khandagiri Square Junction",
      poleRef: "OD-BMC-POLE-3310",
      ward: "Ward 55 (Khandagiri West)",
      coords: [20.2580, 85.7890],
      status: "ONLINE",
      frequency: "865.400 MHz",
      bandwidth: "125 kHz",
      currentLoadPktsPerMin: 29,
      avgRssi: -90,
      snr: 7.9,
      meshPeers: ["GW-BBSR-05", "GW-BBSR-07"],
      uptimePercentage: "99.72%",
      solarBatteryHealth: "91% (Solar Array 400W)",
      lastKeepAlive: "8 seconds ago"
    },
    {
      id: "GW-BBSR-07",
      name: "Jayadev Vihar Flyover Pole",
      poleRef: "OD-BMC-POLE-6091",
      ward: "Ward 28 (Nayapalli / Jayadev Vihar)",
      coords: [20.3015, 85.8240],
      status: "ONLINE",
      frequency: "865.200 MHz",
      bandwidth: "125 kHz",
      currentLoadPktsPerMin: 54,
      avgRssi: -82,
      snr: 10.1,
      meshPeers: ["GW-BBSR-03", "GW-BBSR-04", "GW-BBSR-06"],
      uptimePercentage: "99.95%",
      solarBatteryHealth: "99% (Mains Feed)",
      lastKeepAlive: "5 seconds ago"
    }
  ],

  // Police Emergency Response PCR Patrol Units (Dial 112 Vehicles)
  pcrUnits: [
    {
      id: "PCR-09",
      callsign: "PATIA-TIGER-9",
      station: "Patia Police Station",
      vehicleType: "Tata Safari Storme Quick Reaction Vehicle (QRV)",
      registration: "OD-02-AZ-4109",
      officer: "SI R. K. Nayak",
      crewCount: 3,
      status: "EN_ROUTE",
      assignedIncidentId: "RN-INC-2026-0941",
      coords: [20.3540, 85.8190],
      speedKmph: 46,
      heading: "NW",
      etaToActiveMin: 2.5,
      phone: "+91 94389 11209",
      fuelLevel: "82%"
    },
    {
      id: "PCR-14",
      callsign: "INFOCITY-DELTA-14",
      station: "Infocity Police Station",
      vehicleType: "Mahindra Scorpio 4x4",
      registration: "OD-02-BW-8814",
      officer: "ASI M. Pattnaik",
      crewCount: 3,
      status: "ON_SCENE",
      assignedIncidentId: "RN-INC-2026-0938",
      coords: [20.3514, 85.8157],
      speedKmph: 0,
      heading: "PARKED",
      etaToActiveMin: 0.0,
      phone: "+91 94389 11214",
      fuelLevel: "76%"
    },
    {
      id: "PCR-03",
      callsign: "CSPUR-RHINO-3",
      station: "Chandrasekharpur Police Station",
      vehicleType: "Toyota Innova Crysta",
      registration: "OD-02-CD-5503",
      officer: "SI P. C. Samal",
      crewCount: 3,
      status: "AVAILABLE",
      assignedIncidentId: null,
      coords: [20.3290, 85.8210],
      speedKmph: 15,
      heading: "SE",
      etaToActiveMin: null,
      phone: "+91 94389 11203",
      fuelLevel: "91%"
    },
    {
      id: "PCR-07",
      callsign: "SAHEED-EAGLE-7",
      station: "Saheed Nagar Police Station",
      vehicleType: "Tata Sumo Gold Patrol",
      registration: "OD-02-AL-1107",
      officer: "Inspector T. K. Dash",
      crewCount: 4,
      status: "PATROLLING",
      assignedIncidentId: null,
      coords: [20.2910, 85.8450],
      speedKmph: 22,
      heading: "N",
      etaToActiveMin: null,
      phone: "+91 94389 11207",
      fuelLevel: "68%"
    },
    {
      id: "PCR-11",
      callsign: "CAPITAL-BRAVO-11",
      station: "Capital Police Station (Unit 6)",
      vehicleType: "Mahindra Bolero Neo Patrol",
      registration: "OD-02-EF-3311",
      officer: "ASI S. Mohanty",
      crewCount: 3,
      status: "AVAILABLE",
      assignedIncidentId: null,
      coords: [20.2720, 85.8270],
      speedKmph: 0,
      heading: "STATIONARY",
      etaToActiveMin: null,
      phone: "+91 94389 11211",
      fuelLevel: "88%"
    }
  ],

  // Municipal CCTV Pole Feeds linked to AI Verification Layer
  cctvCameras: [
    {
      id: "CAM-PATIA-14B",
      name: "Patia Magnetics Junction (North-East Pole)",
      poleId: "OD-BMC-CCTV-1402",
      ward: "Ward 14",
      coords: [20.3564, 85.8176],
      streamUrl: "rtsp://10.14.88.20/live/h264/ch1",
      resolution: "1920x1080 @ 30 FPS",
      opticalZoom: "12x Optical, PTZ Auto-Tracking",
      status: "STREAMING_VERIFIED",
      opticalFlowAnomalyScore: 96,
      nightVisionMode: "True Day/Night IR 850nm Enabled",
      fieldOfView: "108° Wide Axis covering East-Bound Sidewalk & Pedestrian Walkway"
    },
    {
      id: "CAM-KIIT-09",
      name: "KIIT Square Lane 4 Corner",
      poleId: "OD-BMC-CCTV-0988",
      ward: "Ward 07",
      coords: [20.3516, 85.8152],
      streamUrl: "rtsp://10.07.41.15/live/h264/ch1",
      resolution: "1920x1080 @ 30 FPS",
      opticalZoom: "Fixed 4mm Wide Angle",
      status: "STREAMING_VERIFIED",
      opticalFlowAnomalyScore: 92,
      nightVisionMode: "IR Enabled",
      fieldOfView: "92° View covering Balaram Temple Lane Entry"
    },
    {
      id: "CAM-CSPUR-04",
      name: "Damana Square SBI Pole",
      poleId: "OD-BMC-CCTV-0412",
      ward: "Ward 21",
      coords: [20.3248, 85.8188],
      streamUrl: "rtsp://10.21.19.04/live/h264/ch1",
      resolution: "1920x1080 @ 30 FPS",
      opticalZoom: "Fixed 6mm Medium Angle",
      status: "STREAMING_ACTIVE",
      opticalFlowAnomalyScore: 22,
      nightVisionMode: "Day/Ambient Street Lighting",
      fieldOfView: "78° View covering SBI ATM forecourt"
    },
    {
      id: "CAM-JANPATH-02",
      name: "Janpath Saheed Nagar Ram Mandir Crossing",
      poleId: "OD-BMC-CCTV-0201",
      ward: "Ward 32",
      coords: [20.2888, 85.8423],
      streamUrl: "rtsp://10.32.05.02/live/h264/ch1",
      resolution: "2560x1440 2K @ 25 FPS",
      opticalZoom: "32x PTZ Smart Tour",
      status: "STREAMING_ACTIVE",
      opticalFlowAnomalyScore: 18,
      nightVisionMode: "IR Enabled",
      fieldOfView: "360° Continuous Patrol Scan"
    }
  ],

  // Wearables Fleet Telemetry Database (Tier 1 Sample)
  wearablesFleet: [
    {
      deviceId: "RN-WR-9204",
      registeredUser: "Priyanka Mohapatra",
      model: "Rakshak Band X1",
      batteryPercent: 89,
      voltage: "4.12V",
      lastHeartbeat: "14 seconds ago",
      bleRssi: -58,
      buttonClicks: 3,
      accelState: "ANOMALOUS_JERK (3.56G)",
      aesKeyStatus: "VALID_MATCH_KDF2",
      pdrRate: "99.8%",
      status: "TRIGGER_ACTIVE"
    },
    {
      deviceId: "RN-WR-8812",
      registeredUser: "Subhashree Jena",
      model: "Rakshak Pendant Pro",
      batteryPercent: 74,
      voltage: "3.98V",
      lastHeartbeat: "35 seconds ago",
      bleRssi: -64,
      buttonClicks: 0,
      accelState: "FALL_IMPACT (5.76G)",
      aesKeyStatus: "VALID_MATCH_KDF2",
      pdrRate: "99.4%",
      status: "FALL_ALERT"
    },
    {
      deviceId: "RN-WR-4401",
      registeredUser: "Ananya Mishra",
      model: "Rakshak Band X1",
      batteryPercent: 92,
      voltage: "4.15V",
      lastHeartbeat: "2 minutes ago",
      bleRssi: -52,
      buttonClicks: 1,
      accelState: "NORMAL_WALK (1.02G)",
      aesKeyStatus: "VALID_MATCH_KDF2",
      pdrRate: "100%",
      status: "STANDBY"
    },
    {
      deviceId: "RN-WR-7719",
      registeredUser: "Roshni Behera",
      model: "Rakshak Pendant Pro",
      batteryPercent: 68,
      voltage: "3.92V",
      lastHeartbeat: "1 minute ago",
      bleRssi: -61,
      buttonClicks: 3,
      accelState: "REST (0.98G)",
      aesKeyStatus: "VALID_MATCH_KDF2",
      pdrRate: "99.7%",
      status: "STANDBY"
    },
    {
      deviceId: "RN-WR-5014",
      registeredUser: "Tanvi Tripathy",
      model: "Rakshak Band X1",
      batteryPercent: 81,
      voltage: "4.05V",
      lastHeartbeat: "45 seconds ago",
      bleRssi: -59,
      buttonClicks: 0,
      accelState: "NORMAL_REST (0.99G)",
      aesKeyStatus: "VALID_MATCH_KDF2",
      pdrRate: "100%",
      status: "STANDBY"
    },
    {
      deviceId: "RN-WR-3389",
      registeredUser: "Deepika Pradhan",
      model: "Rakshak Band X1",
      batteryPercent: 19,
      voltage: "3.58V",
      lastHeartbeat: "4 minutes ago",
      bleRssi: -72,
      buttonClicks: 0,
      accelState: "NORMAL (1.01G)",
      aesKeyStatus: "VALID_MATCH_KDF2",
      pdrRate: "98.2%",
      status: "LOW_BATTERY_WARNING"
    },
    {
      deviceId: "RN-WR-6102",
      registeredUser: "Smrutirekha Das",
      model: "Rakshak Band X1",
      batteryPercent: 95,
      voltage: "4.18V",
      lastHeartbeat: "18 seconds ago",
      bleRssi: -54,
      buttonClicks: 0,
      accelState: "NORMAL_WALK (1.04G)",
      aesKeyStatus: "VALID_MATCH_KDF2",
      pdrRate: "100%",
      status: "STANDBY"
    },
    {
      deviceId: "RN-WR-5521",
      registeredUser: "Lipsa Routray",
      model: "Rakshak Pendant Pro",
      batteryPercent: 87,
      voltage: "4.10V",
      lastHeartbeat: "50 seconds ago",
      bleRssi: -60,
      buttonClicks: 0,
      accelState: "STATIONARY (0.98G)",
      aesKeyStatus: "VALID_MATCH_KDF2",
      pdrRate: "99.9%",
      status: "STANDBY"
    },
    {
      deviceId: "RN-WR-4889",
      registeredUser: "Madhusmita Nayak",
      model: "Rakshak Band X1",
      batteryPercent: 62,
      voltage: "3.89V",
      lastHeartbeat: "1 minute ago",
      bleRssi: -66,
      buttonClicks: 0,
      accelState: "COMMUTE_TRANSIT (1.12G)",
      aesKeyStatus: "VALID_MATCH_KDF2",
      pdrRate: "99.5%",
      status: "STANDBY"
    },
    {
      deviceId: "RN-WR-3844",
      registeredUser: "Swarnalata Samal",
      model: "Rakshak Pendant Pro",
      batteryPercent: 91,
      voltage: "4.14V",
      lastHeartbeat: "25 seconds ago",
      bleRssi: -55,
      buttonClicks: 0,
      accelState: "NORMAL_REST (0.99G)",
      aesKeyStatus: "VALID_MATCH_KDF2",
      pdrRate: "100%",
      status: "STANDBY"
    },
    {
      deviceId: "RN-WR-2975",
      registeredUser: "Itishree Pattnaik",
      model: "Rakshak Band X1",
      batteryPercent: 78,
      voltage: "4.02V",
      lastHeartbeat: "3 minutes ago",
      bleRssi: -63,
      buttonClicks: 0,
      accelState: "NORMAL_WALK (1.01G)",
      aesKeyStatus: "VALID_MATCH_KDF2",
      pdrRate: "99.6%",
      status: "STANDBY"
    },
    {
      deviceId: "RN-WR-2510",
      registeredUser: "Barsharani Sahoo",
      model: "Rakshak Band X1",
      batteryPercent: 18,
      voltage: "3.56V",
      lastHeartbeat: "5 minutes ago",
      bleRssi: -75,
      buttonClicks: 0,
      accelState: "LOW_ACTIVITY (0.98G)",
      aesKeyStatus: "VALID_MATCH_KDF2",
      pdrRate: "97.4%",
      status: "LOW_BATTERY_WARNING"
    },
    {
      deviceId: "RN-WR-1940",
      registeredUser: "Soumyashree Kanungo",
      model: "Rakshak Pendant Pro",
      batteryPercent: 83,
      voltage: "4.06V",
      lastHeartbeat: "42 seconds ago",
      bleRssi: -58,
      buttonClicks: 0,
      accelState: "NORMAL_WALK (1.05G)",
      aesKeyStatus: "VALID_MATCH_KDF2",
      pdrRate: "100%",
      status: "STANDBY"
    },
    {
      deviceId: "RN-WR-1622",
      registeredUser: "Sonali Priyadarshini",
      model: "Rakshak Band X1",
      batteryPercent: 94,
      voltage: "4.17V",
      lastHeartbeat: "15 seconds ago",
      bleRssi: -50,
      buttonClicks: 0,
      accelState: "NORMAL_REST (0.99G)",
      aesKeyStatus: "VALID_MATCH_KDF2",
      pdrRate: "100%",
      status: "STANDBY"
    },
    {
      deviceId: "RN-WR-1437",
      registeredUser: "Archana Panigrahi",
      model: "Rakshak Band X1",
      batteryPercent: 71,
      voltage: "3.96V",
      lastHeartbeat: "2 minutes ago",
      bleRssi: -62,
      buttonClicks: 0,
      accelState: "COMMUTE_TRANSIT (1.08G)",
      aesKeyStatus: "VALID_MATCH_KDF2",
      pdrRate: "99.8%",
      status: "STANDBY"
    },
    {
      deviceId: "RN-WR-1185",
      registeredUser: "Pragyan Paramita Panda",
      model: "Rakshak Pendant Pro",
      batteryPercent: 96,
      voltage: "4.20V",
      lastHeartbeat: "10 seconds ago",
      bleRssi: -48,
      buttonClicks: 0,
      accelState: "STATIONARY (0.99G)",
      aesKeyStatus: "VALID_MATCH_KDF2",
      pdrRate: "100%",
      status: "STANDBY"
    }
  ],

  // Live LoRa incoming packet log for Tier 2 inspector
  recentPackets: [
    {
      time: "22:48:14.182",
      gateway: "GW-BBSR-01",
      devEui: "70B3D57ED0049204",
      freq: "865.200",
      sf: "SF7",
      rssi: -88,
      snr: "+9.4 dB",
      payloadHex: "7F4A92040188E4B192E0F103A899C74E",
      decoded: { type: "PANIC_TRIPLE_CLICK", accelG: 3.56, battV: 4.12, counter: 4182 }
    },
    {
      time: "22:48:14.240",
      gateway: "GW-BBSR-02",
      devEui: "70B3D57ED0049204",
      freq: "865.200",
      sf: "SF7",
      rssi: -94,
      snr: "+7.1 dB",
      payloadHex: "7F4A92040188E4B192E0F103A899C74E",
      decoded: { type: "PANIC_TRIPLE_CLICK", accelG: 3.56, battV: 4.12, counter: 4182 }
    },
    {
      time: "22:47:58.009",
      gateway: "GW-BBSR-03",
      devEui: "70B3D57ED0044401",
      freq: "865.600",
      sf: "SF7",
      rssi: -76,
      snr: "+12.1 dB",
      payloadHex: "7F4A44010190C11054E0B001F991E14A",
      decoded: { type: "HEARTBEAT_TELEMETRY", accelG: 0.99, battV: 4.15, counter: 1109 }
    },
    {
      time: "22:47:41.882",
      gateway: "GW-BBSR-04",
      devEui: "70B3D57ED0045014",
      freq: "865.200",
      sf: "SF8",
      rssi: -81,
      snr: "+10.4 dB",
      payloadHex: "7F4A50140180B23019E0B202F112D901",
      decoded: { type: "HEARTBEAT_TELEMETRY", accelG: 1.01, battV: 4.05, counter: 890 }
    },
    {
      time: "22:47:20.119",
      gateway: "GW-BBSR-01",
      devEui: "70B3D57ED0043389",
      freq: "865.400",
      sf: "SF8",
      rssi: -92,
      snr: "+6.8 dB",
      payloadHex: "7F4A33890119B00118E0A101C011B104",
      decoded: { type: "BATTERY_LOW_ALERT", accelG: 1.01, battV: 3.58, counter: 642 }
    }
  ],

  // System Analytics aggregates
  analytics: {
    totalRegisteredWearables: 14820,
    activeRelayGateways: 7,
    networkUptime30Days: "99.96%",
    pdrAverage: "99.78%",
    totalIncidentsToday: 9,
    confirmedDistressToday: 2,
    autoFilteredFalsePositives: 7,
    falsePositiveFilteringRate: "98.4%",
    meanTimeToVerifySeconds: 3.4,
    meanTimeToDispatchMinutes: 1.8,
    meanTimeToArriveMinutes: 4.2,
    wardStats: [
      { ward: "Ward 14 (Patia - Infocity)", incidents7Days: 4, avgRespTimeMin: 3.6, gateways: 1, pcrCoverage: "EXCELLENT" },
      { ward: "Ward 07 (KIIT Corridor)", incidents7Days: 5, avgRespTimeMin: 3.2, gateways: 1, pcrCoverage: "EXCELLENT" },
      { ward: "Ward 21 (CSPUR Central)", incidents7Days: 2, avgRespTimeMin: 4.5, gateways: 1, pcrCoverage: "OPTIMAL" },
      { ward: "Ward 32 (Saheed Nagar)", incidents7Days: 3, avgRespTimeMin: 3.9, gateways: 1, pcrCoverage: "EXCELLENT" },
      { ward: "Ward 40 (Master Canteen)", incidents7Days: 6, avgRespTimeMin: 4.1, gateways: 1, pcrCoverage: "OPTIMAL" },
      { ward: "Ward 55 (Khandagiri)", incidents7Days: 2, avgRespTimeMin: 5.2, gateways: 1, pcrCoverage: "GOOD" },
      { ward: "Ward 28 (Nayapalli / Jayadev)", incidents7Days: 3, avgRespTimeMin: 3.8, gateways: 1, pcrCoverage: "EXCELLENT" }
    ]
  }
};
